project_name: enma

release:
  github:
    owner: magicdrive
    name: enma
  draft: false
  prerelease: false

builds:
  - id: enma
    goos:
      - linux
      - darwin
      - windows
    ignore:
      - goos: darwin
        goarch: 386
    ldflags:
      - -s -w -X "main.version=v{{.Version}}"
    env:
      - CGO_ENABLED=0
    binary: enma
    main: ./main.go

archives:
  - id: tar.gz
    format: tar.gz
  - id: binary
    format: binary

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

brews:
  - name: enma
    repository:
      owner: magicdrive
      name: homebrew-magicdrive
      branch: main
    homepage: "https://github.com/magicdrive/enma"
    description: "Yet another integration software with file monitoring."
    license: "MIT"
    ids: [tar.gz]
    install: |
      bin.install "enma"
    test: |
      system "#{bin}/enma", "--version"
    commit_author:
      name: magicdrive bot
      email: hiroshi.ikegami+githubbot@magicdrive.jp

