[subcommand]
# Which subcommand this config should use
use = "hotload"

[subcommand.hotload]
# Basic process configuration
daemon = "./myapp"
pre_build = "echo pre-build step. event by {}"
build = "go build -o ./myapp ./cmd/myapp"
post_build = "echo post-build done event by {}"
signal = "SIGTERM"
working_dir = "./"
build_at_start = true

# command args
placeholder = "{}"
absolute_path = true
args_path_style = "dirname,basename,ext"

# Timing and retry
timeout = "5s"
delay = "0s"
retry = 1
check_content_diff = false

# Watch target configuration
watch_dir = ["./"]
pattern_regex = ".*"
include_ext = [".go", ".mod"]
ignore_regex = "_test.go$"
exclude_ext = [".tmp"]
exclude_dir = [".git", "tmp", "vendor", ".enma"]
default_ignores = "minimal"
enmaignore = [".enmaignore"]

# File paths
## logs = "" # should be logging off.
logs = "./.enma/log/enma_hotload.log"
## pid = "" # should be pid output off.
pid = "./.enma/run/enma_watch.pid"

